### ISSUE TITLE
@fluent/bundle 0.17.0 broke @microsoft/api-extractor

### ISSUE THREAD

**Issue by Demivan** [projectfluent/fluent.js#574]
I was using `@microsoft/api-extractor` to generate one file with Typescript type definitions for my `fluent-vue` library. With 0.17.0 version of `@fluent/bundle` it stopped working.

Looks like  `@microsoft/api-extractor` finds package.json in esm/ folder. But package.json there does not have package name set and api-extractor fails.

```
(node:1794) UnhandledPromiseRejectionWarning: Error: Error reading "/home/runner/work/fluent-vue/fluent-vue/node_modules/@fluent/bundle/esm/package.json":
  The required field "name" was not found
    at PackageJsonLookup.loadNodePackageJson (/home/runner/work/fluent-vue/fluent-vue/node_modules/@rushstack/node-core-library/lib/PackageJsonLookup.js:219:23)
    at PackageMetadataManager.tryFetchPackageMetadata (/home/runner/work/fluent-vue/fluent-vue/node_modules/@microsoft/api-extractor/lib/analyzer/PackageMetadataManager.js:133:57)
    at PackageMetadataManager.isAedocSupportedFor (/home/runner/work/fluent-vue/fluent-vue/node_modules/@microsoft/api-extractor/lib/analyzer/PackageMetadataManager.js:151:38)
    at AstSymbolTable._fetchAstSymbol (/home/runner/work/fluent-vue/fluent-vue/node_modules/@microsoft/api-extractor/lib/analyzer/AstSymbolTable.js:451:51)
    at ExportAnalyzer._fetchAstImport (/home/runner/work/fluent-vue/fluent-vue/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:704:60)
    at ExportAnalyzer._tryMatchImportDeclaration (/home/runner/work/fluent-vue/fluent-vue/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:505:33)
    at ExportAnalyzer.fetchReferencedAstEntity (/home/runner/work/fluent-vue/fluent-vue/node_modules/@microsoft/api-extractor/lib/analyzer/ExportAnalyzer.js:288:45)
    at AstSymbolTable._analyzeChildTree (/home/runner/work/fluent-vue/fluent-vue/node_modules/@microsoft/api-extractor/lib/analyzer/AstSymbolTable.js:328:76)
    at AstSymbolTable._analyzeChildTree (/home/runner/work/fluent-vue/fluent-vue/node_modules/@microsoft/api-extractor/lib/analyzer/AstSymbolTable.js:373:18)
    at AstSymbolTable._analyzeChildTree (/home/runner/work/fluent-vue/fluent-vue/node_modules/@microsoft/api-extractor/lib/analyzer/AstSymbolTable.js:373:18)
```

It is just a heads up. For now, I just stopped using `@microsoft/api-extractor` but I'm not sure if having package.json without name property is correctly handled by other tools.

**Comment by eemeli** [comment]
It looks like this is caused by microsoft/rushstack#2070, and it is an error specific to api-extractor.

**Comment by Demivan** [comment]
Then I'm closing this. If bundlers are working correctly then this should be fixed on an api-extractor side.
